services:

  
  app:
    image: lmarin70/ia_animalitos-app:latest
    build: .
    container_name: ia_animalitos
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"

    