# Generated by Django 4.2.1 on 2023-07-08 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('articulo', models.CharField(max_length=30)),
                ('tipo_unidad', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField(help_text='En stock', verbose_name='Cantidad')),
                ('precio_sugerido_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio sugerido de venta')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50, null=True, verbose_name='Cliente')),
                ('ci_rif', models.CharField(max_length=20, null=True, verbose_name='Cedula o RIF')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio/unidad')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='SubTotal')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('articulo', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='licoreriaapp.articulo')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
