# Generated by Django 4.2.1 on 2023-07-09 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_guardia',
            fields=[
                ('codigo_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Stock')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_articulo', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='licoreriaapp.articulo', verbose_name='Articulo')),
            ],
        ),
    ]
