# Generated by Django 4.2.1 on 2023-07-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0002_inventario_guardia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario_guardia',
        ),
    ]
