# Generated by Django 4.2.1 on 2023-07-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0003_delete_inventario_guardia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='articulo',
            new_name='codigo_articulo',
        ),
    ]
