# Generated by Django 4.2.1 on 2023-07-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0004_rename_articulo_venta_codigo_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigo_articulo',
            new_name='articulo',
        ),
    ]
