# Generated by Django 4.2.1 on 2023-07-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0005_rename_codigo_articulo_venta_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
