# Generated by Django 4.2.1 on 2023-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreriaapp', '0009_remove_venta_cantidad_remove_venta_codigo_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='totalbolivares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total Bolivares'),
        ),
    ]
